[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "KnowledgeBase"
authors = [{name = "celikelozdinc", email = "ozdinc.celikel@gmail.com"}]
dynamic = ["version", "description"]
